/** Preview WhatsApp formatting for all reports */
const tdl = require('../tdl');

const stmtXml = `<ENVELOPE>
  <VOUCHER VCHTYPE="Sales"><DATE>20260115</DATE><VOUCHERTYPENAME>Sales</VOUCHERTYPENAME><VOUCHERNUMBER>S100</VOUCHERNUMBER><NARRATION>Invoice for Jan batch</NARRATION><AMOUNT>-15000</AMOUNT><PARTYLEDGERNAME>Meril</PARTYLEDGERNAME></VOUCHER>
  <VOUCHER VCHTYPE="Receipt"><DATE>20260120</DATE><VOUCHERTYPENAME>Receipt</VOUCHERTYPENAME><VOUCHERNUMBER>R100</VOUCHERNUMBER><NARRATION>Payment received</NARRATION><AMOUNT>10000</AMOUNT><PARTYLEDGERNAME>Meril</PARTYLEDGERNAME></VOUCHER>
  <VOUCHER VCHTYPE="Sales"><DATE>20260205</DATE><VOUCHERTYPENAME>Sales</VOUCHERTYPENAME><VOUCHERNUMBER>S101</VOUCHERNUMBER><NARRATION>Feb invoice</NARRATION><AMOUNT>-8500</AMOUNT><PARTYLEDGERNAME>Meril</PARTYLEDGERNAME></VOUCHER>
</ENVELOPE>`;

console.log('=== LEDGER STATEMENT ===');
console.log(tdl.parseLedgerStatementTdlResponse(stmtXml, 'Meril Life Sciences Pvt Ltd', 20).message);

const vchXml = `<ENVELOPE>
  <VOUCHER VCHTYPE="Sales"><DATE>20260219</DATE><VOUCHERTYPENAME>Sales</VOUCHERTYPENAME><VOUCHERNUMBER>S200</VOUCHERNUMBER><NARRATION>Office supplies</NARRATION><AMOUNT>-12000</AMOUNT><PARTYLEDGERNAME>Party A</PARTYLEDGERNAME></VOUCHER>
  <VOUCHER VCHTYPE="Payment"><DATE>20260219</DATE><VOUCHERTYPENAME>Payment</VOUCHERTYPENAME><VOUCHERNUMBER>P50</VOUCHERNUMBER><NARRATION>Rent payment</NARRATION><AMOUNT>25000</AMOUNT><PARTYLEDGERNAME>Landlord</PARTYLEDGERNAME></VOUCHER>
  <VOUCHER VCHTYPE="Receipt"><DATE>20260219</DATE><VOUCHERTYPENAME>Receipt</VOUCHERTYPENAME><VOUCHERNUMBER>R30</VOUCHERNUMBER><NARRATION>Client payment</NARRATION><AMOUNT>50000</AMOUNT><PARTYLEDGERNAME>Party B</PARTYLEDGERNAME></VOUCHER>
</ENVELOPE>`;

console.log('\n=== DAYBOOK ===');
console.log(tdl.parseVouchersTdlResponse(vchXml, 50, '20260219', '20260219').message);

const spXml = `<ENVELOPE>
  <VOUCHER VCHTYPE="Sales"><DATE>20260201</DATE><VOUCHERNUMBER>S300</VOUCHERNUMBER><AMOUNT>-45000</AMOUNT><PARTYLEDGERNAME>Alpha Corp</PARTYLEDGERNAME></VOUCHER>
  <VOUCHER VCHTYPE="Sales"><DATE>20260205</DATE><VOUCHERNUMBER>S301</VOUCHERNUMBER><AMOUNT>-32000</AMOUNT><PARTYLEDGERNAME>Alpha Corp</PARTYLEDGERNAME></VOUCHER>
  <VOUCHER VCHTYPE="Sales"><DATE>20260210</DATE><VOUCHERNUMBER>S302</VOUCHERNUMBER><AMOUNT>-18000</AMOUNT><PARTYLEDGERNAME>Beta Ltd</PARTYLEDGERNAME></VOUCHER>
  <VOUCHER VCHTYPE="Sales"><DATE>20260215</DATE><VOUCHERNUMBER>S303</VOUCHERNUMBER><AMOUNT>-9500</AMOUNT><PARTYLEDGERNAME>Gamma Inc</PARTYLEDGERNAME></VOUCHER>
</ENVELOPE>`;

console.log('\n=== SALES REPORT ===');
console.log(tdl.parseSalesPurchaseReportTdlResponse(spXml, 'sales', '20260201', '20260228').message);

const outXml = `<ENVELOPE>
  <LEDGER NAME="Alpha Corp"><CLOSINGBALANCE>-75000</CLOSINGBALANCE></LEDGER>
  <LEDGER NAME="Beta Ltd"><CLOSINGBALANCE>-32000</CLOSINGBALANCE></LEDGER>
  <LEDGER NAME="Gamma Inc"><CLOSINGBALANCE>-12500</CLOSINGBALANCE></LEDGER>
</ENVELOPE>`;

console.log('\n=== OUTSTANDING ===');
console.log(tdl.parseOutstandingTdlResponse(outXml, 'Sundry Debtors').message);

const listXml = `<ENVELOPE>
  <LEDGER NAME="HDFC Bank"><NAME>HDFC Bank</NAME><PARENT>Bank Accounts</PARENT></LEDGER>
  <LEDGER NAME="SBI Current"><NAME>SBI Current</NAME><PARENT>Bank Accounts</PARENT></LEDGER>
  <LEDGER NAME="Petty Cash"><NAME>Petty Cash</NAME><PARENT>Cash-in-Hand</PARENT></LEDGER>
</ENVELOPE>`;

console.log('\n=== LIST LEDGERS ===');
console.log(tdl.parseListLedgersTdlResponse(listXml).message);

// ── New Reports ──

const cashBankXml = `<ENVELOPE>
  <LEDGER NAME="HDFC Bank"><NAME>HDFC Bank</NAME><PARENT>Bank Accounts</PARENT><CLOSINGBALANCE>-250000.50</CLOSINGBALANCE></LEDGER>
  <LEDGER NAME="SBI Current"><NAME>SBI Current</NAME><PARENT>Bank Accounts</PARENT><CLOSINGBALANCE>-180000</CLOSINGBALANCE></LEDGER>
  <LEDGER NAME="Petty Cash"><NAME>Petty Cash</NAME><PARENT>Cash-in-Hand</PARENT><CLOSINGBALANCE>-15000</CLOSINGBALANCE></LEDGER>
</ENVELOPE>`;

console.log('\n=== CASH & BANK BALANCE ===');
console.log(tdl.parseCashBankBalanceTdlResponse(cashBankXml).message);

const plXml = `<ENVELOPE>
  <GROUP NAME="Sales Accounts"><NAME>Sales Accounts</NAME><PARENT>Profit &amp; Loss A/c</PARENT><CLOSINGBALANCE>-500000</CLOSINGBALANCE></GROUP>
  <GROUP NAME="Direct Income"><NAME>Direct Income</NAME><PARENT>Profit &amp; Loss A/c</PARENT><CLOSINGBALANCE>-50000</CLOSINGBALANCE></GROUP>
  <GROUP NAME="Direct Expenses"><NAME>Direct Expenses</NAME><PARENT>Profit &amp; Loss A/c</PARENT><CLOSINGBALANCE>200000</CLOSINGBALANCE></GROUP>
  <GROUP NAME="Indirect Expenses"><NAME>Indirect Expenses</NAME><PARENT>Profit &amp; Loss A/c</PARENT><CLOSINGBALANCE>150000</CLOSINGBALANCE></GROUP>
</ENVELOPE>`;

console.log('\n=== PROFIT & LOSS ===');
console.log(tdl.parseProfitLossTdlResponse(plXml, '20250401', '20260219').message);

const expXml = `<ENVELOPE>
  <LEDGER NAME="Salary"><NAME>Salary</NAME><PARENT>Indirect Expenses</PARENT><CLOSINGBALANCE>120000</CLOSINGBALANCE></LEDGER>
  <LEDGER NAME="Rent"><NAME>Rent</NAME><PARENT>Indirect Expenses</PARENT><CLOSINGBALANCE>50000</CLOSINGBALANCE></LEDGER>
  <LEDGER NAME="Freight"><NAME>Freight</NAME><PARENT>Direct Expenses</PARENT><CLOSINGBALANCE>15000</CLOSINGBALANCE></LEDGER>
  <LEDGER NAME="Electricity"><NAME>Electricity</NAME><PARENT>Indirect Expenses</PARENT><CLOSINGBALANCE>8500</CLOSINGBALANCE></LEDGER>
</ENVELOPE>`;

console.log('\n=== EXPENSE REPORT ===');
console.log(tdl.parseExpenseReportTdlResponse(expXml, '20260201', '20260219').message);

const stockXml = `<ENVELOPE>
  <STOCKITEM NAME="Widget A"><NAME>Widget A</NAME><PARENT>Finished Goods</PARENT><CLOSINGBALANCE>500 Nos</CLOSINGBALANCE><CLOSINGRATE>120</CLOSINGRATE><CLOSINGVALUE>60000</CLOSINGVALUE></STOCKITEM>
  <STOCKITEM NAME="Widget B"><NAME>Widget B</NAME><PARENT>Finished Goods</PARENT><CLOSINGBALANCE>200 Kg</CLOSINGBALANCE><CLOSINGRATE>250</CLOSINGRATE><CLOSINGVALUE>50000</CLOSINGVALUE></STOCKITEM>
  <STOCKITEM NAME="Raw Material X"><NAME>Raw Material X</NAME><PARENT>Raw Materials</PARENT><CLOSINGBALANCE>1000 Nos</CLOSINGBALANCE><CLOSINGRATE>15</CLOSINGRATE><CLOSINGVALUE>15000</CLOSINGVALUE></STOCKITEM>
</ENVELOPE>`;

console.log('\n=== STOCK SUMMARY ===');
console.log(tdl.parseStockSummaryTdlResponse(stockXml).message);

const gstXml = `<ENVELOPE>
  <LEDGER NAME="CGST Output"><NAME>CGST Output</NAME><PARENT>Duties &amp; Taxes</PARENT><CLOSINGBALANCE>-25000</CLOSINGBALANCE></LEDGER>
  <LEDGER NAME="SGST Output"><NAME>SGST Output</NAME><PARENT>Duties &amp; Taxes</PARENT><CLOSINGBALANCE>-25000</CLOSINGBALANCE></LEDGER>
  <LEDGER NAME="CGST Input"><NAME>CGST Input</NAME><PARENT>Duties &amp; Taxes</PARENT><CLOSINGBALANCE>10000</CLOSINGBALANCE></LEDGER>
  <LEDGER NAME="SGST Input"><NAME>SGST Input</NAME><PARENT>Duties &amp; Taxes</PARENT><CLOSINGBALANCE>10000</CLOSINGBALANCE></LEDGER>
</ENVELOPE>`;

console.log('\n=== GST SUMMARY ===');
console.log(tdl.parseGstSummaryTdlResponse(gstXml, '20260201', '20260219').message);

const billXml = `<ENVELOPE>
  <BILL NAME="INV-001"><NAME>INV-001</NAME><PARENT>Meril</PARENT><CLOSINGBALANCE>-35000</CLOSINGBALANCE><FINALDUEDATE>20260115</FINALDUEDATE></BILL>
  <BILL NAME="INV-002"><NAME>INV-002</NAME><PARENT>Meril</PARENT><CLOSINGBALANCE>-20000</CLOSINGBALANCE><FINALDUEDATE>20260315</FINALDUEDATE></BILL>
</ENVELOPE>`;

console.log('\n=== BILL OUTSTANDING ===');
console.log(tdl.parseBillOutstandingTdlResponse(billXml, 'Meril Life Sciences Pvt Ltd').message);
